#基本配置
RUN_MODE: "debug"
#app
PAGE_SIZE: "10"
JWT_SECRET: "1120&0708"
#server
HTTP_PORT: "8080"
#6s
READ_TIMEOUT: 6000000000
WRITE_TIMEOUT: 6000000000
#database
TYPE: "mysql"
USER: "root"
PASSWORD: "123456"
HOST: "127.0.0.1:3306"
NAME: "ginblog"
TABLE_PREFIX: "ginblog_"
